// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ticker_command.proto

package ticker_command

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TickerCommand_Command int32

const (
	TickerCommand_STOP  TickerCommand_Command = 0
	TickerCommand_PLAY  TickerCommand_Command = 1
	TickerCommand_PAUSE TickerCommand_Command = 2
	TickerCommand_CLEAR TickerCommand_Command = 3
)

var TickerCommand_Command_name = map[int32]string{
	0: "STOP",
	1: "PLAY",
	2: "PAUSE",
	3: "CLEAR",
}

var TickerCommand_Command_value = map[string]int32{
	"STOP":  0,
	"PLAY":  1,
	"PAUSE": 2,
	"CLEAR": 3,
}

func (x TickerCommand_Command) String() string {
	return proto.EnumName(TickerCommand_Command_name, int32(x))
}

func (TickerCommand_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_671e1ac418e7564b, []int{0, 0}
}

type TickerCommand struct {
	Command              TickerCommand_Command `protobuf:"varint,1,opt,name=command,proto3,enum=TickerCommand_Command" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TickerCommand) Reset()         { *m = TickerCommand{} }
func (m *TickerCommand) String() string { return proto.CompactTextString(m) }
func (*TickerCommand) ProtoMessage()    {}
func (*TickerCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_671e1ac418e7564b, []int{0}
}

func (m *TickerCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TickerCommand.Unmarshal(m, b)
}
func (m *TickerCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TickerCommand.Marshal(b, m, deterministic)
}
func (m *TickerCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TickerCommand.Merge(m, src)
}
func (m *TickerCommand) XXX_Size() int {
	return xxx_messageInfo_TickerCommand.Size(m)
}
func (m *TickerCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_TickerCommand.DiscardUnknown(m)
}

var xxx_messageInfo_TickerCommand proto.InternalMessageInfo

func (m *TickerCommand) GetCommand() TickerCommand_Command {
	if m != nil {
		return m.Command
	}
	return TickerCommand_STOP
}

func init() {
	proto.RegisterEnum("TickerCommand_Command", TickerCommand_Command_name, TickerCommand_Command_value)
	proto.RegisterType((*TickerCommand)(nil), "TickerCommand")
}

func init() {
	proto.RegisterFile("ticker_command.proto", fileDescriptor_671e1ac418e7564b)
}

var fileDescriptor_671e1ac418e7564b = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0xc9, 0x4c, 0xce,
	0x4e, 0x2d, 0x8a, 0x4f, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x57, 0x2a, 0xe3, 0xe2, 0x0d, 0x01, 0x8b, 0x3b, 0x43, 0x84, 0x85, 0x0c, 0xb8, 0xd8, 0xa1, 0x2a,
	0x24, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0xc4, 0xf4, 0x50, 0x14, 0xe8, 0x41, 0xe9, 0x20, 0x98,
	0x32, 0x25, 0x63, 0x2e, 0x76, 0x98, 0x66, 0x0e, 0x2e, 0x96, 0xe0, 0x10, 0xff, 0x00, 0x01, 0x06,
	0x10, 0x2b, 0xc0, 0xc7, 0x31, 0x52, 0x80, 0x51, 0x88, 0x93, 0x8b, 0x35, 0xc0, 0x31, 0x34, 0xd8,
	0x55, 0x80, 0x09, 0xc4, 0x74, 0xf6, 0x71, 0x75, 0x0c, 0x12, 0x60, 0x4e, 0x62, 0x03, 0x5b, 0x6f,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xdb, 0x36, 0xbc, 0x96, 0x00, 0x00, 0x00,
}
